
#////////////////////////////////////////////////////////////////////
# Makefile				
#////////////////////////////////////////////////////////////////////

#////////////////////////////////////////////////////////////////////
#				Compiler and Linker flags
#////////////////////////////////////////////////////////////////////
CFLAGS  = -O -g
LINKER  = -Xlinker -Map -Xlinker mapfile -Xlinker -Ttext -Xlinker 80140000
RM	= rm


PROG = main
OBJS = main.o game.o sound.o

all: $(PROG)


$(PROG): $(OBJS) 
	$(CC) $(OBJS) $(LINKER) -o $(PROG)

main.o:    main.c main.h cntrl.h game.h

game.o:    game.c game.h cntrl.h main.h

sound.o:   sound.c sound.h game.h cntrl.h main.h




