/* $PSLibId: Run-time Library Release 4.0$ */
/*
 *	TMD ID List for "te.tmd"
 *
 *		 Created by rsdlink(v3.6) at 13:31 12/12/94
 *
 *	(C) 1994 Sony Computer Entertainment Inc. All Rights Reserved.
 */

int te_list[] = {
	1,	/* OBJ0 */
	2,	/* OBJ1_1 */
	3,	/* OBJ1_2 */
	4,	/* OBJ2_1 */
	5,	/* OBJ2_2 */
	6,	/* OBJ2_3 */
	7,	/* OBJ3_1 */
	8,	/* OBJ3_2 */
	9,	/* OBJ3_3 */
	10,	/* OBJ4_1 */
	11,	/* OBJ4_2 */
	12,	/* OBJ4_3 */
	13,	/* OBJ5_1 */
	14,	/* OBJ5_2 */
	15,	/* OBJ5_3 */
};
