CC=mips-unknown-ecoff-gcc
STRIP=mips-unknown-ecoff-strip
CFLAGS	= -Wall
LINKER  = -Xlinker -Ttext -Xlinker 80140000

PROG	=	main.exe
OBJS    =    main.o pad.o

all: $(PROG)

$(PROG): $(OBJS)
	$(CC) $(LINKER) $(OBJS) -o $@
	$(STRIP) $@

.c.o:
	$(CC) $(CFLAGS) -funsigned-char -c $<

run: $(PROG)	
	rm -f psx.exe 
	yarexe auto	
	nopsx psx.exe	

sio: $(PROG)	
		call cmd /C wincmd minicons.exe auto

clean:
	rm $(PROG)
	rm *.o
	rm psx.exe 
